<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9ce8ffb8-724b-4ffc-85bb-e5b7e49d7e61</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <None Update="MockSap/*.xml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
